### ISSUE TITLE
[FEATURE]: Create NumberFormat Page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#15]
## Summary

Like it is being done to the DateTimeFormat page let's do the same for NumberFormat page.

This issue will be labeled as `EPIC` so that PR`s for smaller parts can be open.
Ex: Layout, Links, Popovers, Form, Display (Result), Change Number, etc...

### Progress

- [ ] Layout
- [ ] Data
- [ ] Form
- [ ] Links

### Basic example

Omit this section if it's not applicable.
![image](https://user-images.githubusercontent.com/9373787/66743860-cb89d100-ee72-11e9-81f6-4b3d7cd8f491.png)

### Motivation

Continue adding pages 🎉

**Comment by Muskan284** [comment]
Can i try this one

**Comment by luisFilipePT** [comment]
@Muskan284 sure, I would suggest starting with a PR just for the layout with hardcoded data for now.

What do you think? 🤔

**Comment by Muskan284** [comment]
> @Muskan284 sure, I would suggest starting with a PR just for the layout with hardcoded data for now.
> 
> What do you think? thinking

yes i am starting with hardcoded data

**Comment by luisFilipePT** [comment]
@Muskan284 the code changed a lot since the last time you've pushed, going to remove you from assignee's and reopen the task in case you are still interested add comment to check the best approach.

👍 thanks for the effort

This issue is now `up for grabs` again 😄

**Comment by coderavels** [comment]
Would like to take this up.

**Comment by luisFilipePT** [comment]
Great, go for it @heisfullstacked

**Comment by coderavels** [comment]
Working on this today.
