### ISSUE TITLE
[FEATURE]: Add share on twitter

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#19]
## Summary

Add share on twitter with a beautiful post that suggests to follow @xgeeksio

Any question just tag me in a comment and will try to respond the faster I can
### Basic example

A very rough sketch below just for placement

![image](https://user-images.githubusercontent.com/9373787/66768811-61415280-eeab-11e9-8fcb-c2f0d3ecf06f.png)

### Motivation

When ready help share knowledge because sharing is caring 👐 😄

**Comment by lawrence-dass** [comment]
I'd like work on this, please.

**Comment by luisFilipePT** [comment]
go for it 🚀 @Lawrence4code 
Thanks 🙌

**Comment by flaviohenriqu** [comment]
#26 PR Open
