### ISSUE TITLE
[FEATURE]: Dark Mode (with toggle)

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#2]
## Summary

Brief explanation of the feature.
Add Dark mode and respective Toggle Icon.

### Basic example
Something like https://www.gatsbyjs.org/ has on their docs would be awesome
![image](https://user-images.githubusercontent.com/9373787/66725013-ce5dd500-ee24-11e9-8e61-770bf42aa13c.png)

Omit this section if it's not applicable.

### Motivation
Its really cool 😎 and less stressful for the 👀

**Comment by amytsao** [comment]
I could probably pick this up! Are you okay if I changed the css to use a library like Emotion?

**Comment by luisFilipePT** [comment]
Hi, thanks for the support 👏 

No problem  in using `Emotion` since we are just starting but would it be possible to use `styled-components` instead?  🤔 Its just that some of the guys here have more experience on that 😄.

But anyway I will assign you and you decide the best way 😉 
@amytsao go for it 🚀

**Comment by amytsao** [comment]
Okay! Styled-components also has a ThemeProvider so that should be okay :D

**Comment by luisFilipePT** [comment]
@amytsao are you still working on this?
