### ISSUE TITLE
[BUG]: Improve sentences written in "About this page" section

### ISSUE THREAD

**Issue by comoser** [xgeekshq/js-intl-kitchen-sink#21]
## Description

In the "About this page" section of the home page, there are some sentences that could be improved, semantically and grammatically, strictly speaking of the english language.

### Steps to reproduce

Just open https://js-intl-kitchen-sink.netlify.com/ and verify the section.

### Expected result

N/A

### Actual result

N/A

**Comment by luisFilipePT** [comment]
thanks @comoser , feel free to open a PR 👐
