### ISSUE TITLE
[FEATURE]: Scroll to top

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#25]
## Summary
Add a nice scroll to top in the bottom right corner of the template. So that the all pages in the future have this functionality.
Use this to keep consistency https://ant.design/components/back-top/ 😄 
### Basic example
![image](https://user-images.githubusercontent.com/9373787/66776182-bf773100-eebd-11e9-80c6-bae939d15921.png)

Omit this section if it's not applicable.

### Motivation

Has the pages grow in height, the top should be easier to navigate to.

**Comment by guilhermeorcezi** [comment]
I can work on this.

**Comment by luisFilipePT** [comment]
go for it @guilhermeorcezi  💪

**Comment by connor-payne** [comment]
Have completed

**Comment by luisFilipePT** [comment]
@guilhermeorcezi got mixed up and approved a PR regarding this issue that was not yours, my apologies 🙏 , I will add you the same to the list of contributors, and I will try to be more careful next time.

Keep an 👁 that I will probably add a few more issues tonight or tomorrow morning.

@all-contributors please add @guilhermeorcezi  for code

**Comment by luisFilipePT** [comment]
@all-contributors please add @guilhermeorcezi for code

**Comment by luisFilipePT** [comment]
@connor-payne on the next issue you tackle 😃 please make sure there is no one assigned yet and if there is please inform that user of your intent 🤝 

Again @connor-payne and @guilhermeorcezi thanks so much, good work!

**Comment by connor-payne** [comment]
@luisFilipePT and  @guilhermeorcezi apologies for the mix up. My first PR.
