### ISSUE TITLE
[FEATURE]: Complete DateTimeFormat form options

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#3]
## Summary . 
The DateTimeFormat page meant to serve as an example and at this point it only has 2 fields(location and dateStyle).
This issue is to complete the form.
 
Brief explanation of the feature.
Complete the form with all options that can be found on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat.
Choose the best form components from antd for the possible value.
https://ant.design/docs/react/introduce

Note: Do not worry too much about the options of the elements a separated issue exists.

### Motivation
 To provide the best experience to the user and make information on the form clear and intuitive to the user.

**Comment by jfrato** [comment]
Can I grab this issue?

**Comment by luisFilipePT** [comment]
Sure, have a blast 🚀

**Comment by luisFilipePT** [comment]
#17

**Comment by luisFilipePT** [comment]
@all-contributors please add @jratoxgeeks  for code
