### ISSUE TITLE
[BUG]: No 404 Page on Invalid URL just a blank page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#31]
## Description

When I navigate to some unknown url (ex: https://js-intl-kitchen-sink.netlify.com/abc)

Netlify default Not Found page
![image](https://user-images.githubusercontent.com/9373787/66780474-c7889e00-eec8-11e9-98ff-d9fc6b4f5c46.png)

### Steps to reproduce

Navigate to a route that doesn't exist

### Expected result

You should see a beautiful 404 Page

![image](https://user-images.githubusercontent.com/9373787/66780541-f868d300-eec8-11e9-98f1-44b52267e8c3.png)

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/9373787/66780567-06b6ef00-eec9-11e9-8ae0-47b47f5bce48.png)

**Comment by harshanarisetty** [comment]
Can I work on this?

**Comment by luisFilipePT** [comment]
Sure, go for it 🚀

**Comment by smrsan76** [comment]
Hi...
Where is your 404 page?
I've forked your repo ...
But I didn't find it.

**Comment by smrsan76** [comment]
Uh oh...!
I think that the issue is just taken an I can't help you anymore.
Am I right..?

**Comment by luisFilipePT** [comment]
@smrsan76 there's a component not a page yet, But the issue was just assigned if you want to work together please arrange among yourselves.

Good work 👐🤝

**Comment by PeterSherk** [comment]
Just add the following to the end of the Routes:

`<Route component={notImplemented} />`

**Comment by hackzor4** [comment]
Hi, I already fixed this, but for some reason it doesn't allow me to push the changes :-/

**Comment by PeterSherk** [comment]
@hackzor4  are you trying to push directly to master? You'll have to make a branch and submit a PR

**Comment by hackzor4** [comment]
I have my own branch 404_fix but I think I may need some permission to push the changes?
It gives me: 

remote: Permission to xgeekshq/js-intl-kitchen-sink.git denied to hackzor4.
fatal: unable to access 'https://github.com/xgeekshq/js-intl-kitchen-sink.git/': The requested URL returned error: 403

Maybe only the assignee may push into the repo?

**Comment by luisFilipePT** [comment]
@hackzor4 the issue is already taken by @harshanarisetty , please request his feedback if he has already started or if you can submit a PR 🤝.

Keep an 👁 that I will post issues frequently in this first days of the project 😄 even if we are unable to merge your PR since the issues was already assigned.

Regarding the permissions you need to:
1 - Create a fork from this repo
2 - Make and Commit you changes to a branch on your forked repo
3 - When finished push to your repo
4 - From your repo open a PR against the master branch of this repo

 "Maybe only the assignee may push into the repo?" - NO the flow is the same for everyone.

More detailed instructions here -  https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

So, you can open the PR and we will even review it but it will only get accepted if @harshanarisetty passes the issue to your or don't reply in the next 2/3 days.

🙌 thanks for the help 🚀 keep up the good work

Cheers

**Comment by luisFilipePT** [comment]
@harshanarisetty when possible share your feedback in this thread 👂 😄
