### ISSUE TITLE
[FEATURE]:Add search to selects with more than 6 options 

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#33]
## Summary

Add search  to selects with more than 6 options

### Basic example

https://ant.design/components/select/
![image](https://user-images.githubusercontent.com/9373787/66788618-2ad1fa80-eee0-11e9-8beb-d7657984917e.png)

### Motivation

Facilitate option selection

**Comment by khuongTiet** [comment]
Opening a PR for this https://github.com/xgeekshq/js-intl-kitchen-sink/pull/63
