### ISSUE TITLE
[FEATURE]: Improve Documentation - Contributing guide

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#37]
## Summary

Improve our CONTRIBUTING doc (focus on `Getting Started Section`) maintaining a good layout

Minimal information it should contain :
- [ ] Prerequisites (node, yarn or npm), link to external pages how to install
- [ ] How to run the project in steps with code for each step
- [ ] We use `antd` as the component framework, link to antd and state that you should look for components here first 
- [ ] We are on the latest version of React and we favour functional components and hooks to class components
- [ ] We also multiple small components to a big one
- [ ] Styling is using css modules, external link to info about this, leave classic css to global styles
- [ ] Prettier guarantees the code style adopted and runs on commit, stick to this code style
- [ ] Commits should follow the conventional commits guidelines link and give a code example
- [ ] Opening pull requests should be done using the github template, with enough information and screenshots for visual changes to facilitate the reviewer job. Its MANDATORY to add a link to the issue related

### Motivation

Help make contributions easier and facilitate everyone tasks

**Comment by gzine** [comment]
Made attempt to improve Contributing Guide. 
Created Pull request.
Waiting on Review.

**Comment by luisFilipePT** [comment]
@gzine left a comment in the review 😄
