### ISSUE TITLE
[FEATURE]: Add rest action to clear the DateTimeFormat form

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#38]
## Summary

Add reset option to clear ALL fields on the form.
We use a reducer and state, so this is what needs to be cleared

### Basic example

![image](https://user-images.githubusercontent.com/9373787/66838322-63afb500-ef5c-11e9-9c28-37aa0405f714.png)

### Motivation

Make the use of the form more fluid

**Comment by GlennHoran** [comment]
I can give this one a bash between today and tomorrow

**Comment by coderavels** [comment]
Would love to take this up

**Comment by luisFilipePT** [comment]
@heisfullstacked assigned 😄
