### ISSUE TITLE
[BUG]: Update SubTitle in main page header

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#39]
## Description

Navigating throw the pages you always see Home as the subtitle of the page.
It should say something related to the page, in a first iteration maybe just the topic human readable

`DateTimeFormat -> Date Time`

### Steps to reproduce

![image](https://user-images.githubusercontent.com/9373787/66838704-11bb5f00-ef5d-11e9-82ba-4e8b26ef5203.png)

### Expected result

Say something in the scope of the page

### Actual result

What happened.

**Comment by geekyrajshri** [comment]
Hi,
I would like to try this

**Comment by luisFilipePT** [comment]
@geekyrajshri go for it 🚀

**Comment by PanchakshariPM** [comment]
Hi I would like to try this.

**Comment by luisFilipePT** [comment]
@geekyrajshri next time please add the reference to the issue in the PR (use the template), if you don't I have to close it by hand 😓 

Thanks for your contribution 🙏
