### ISSUE TITLE
[FEATURE]: Copy to clipboard

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#40]
## Summary

In DateFormat page theres a copy to clipboard action not implemented.
It should copy to the clipboard the code of the DateTimeFormat function with the data of the form.

ex:
```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
const formattedDate = new Intl.DateTimeFormat('en-US', {
  year: 'numeric', month: 'numeric', day: 'numeric',
  hour: 'numeric', minute: 'numeric', second: 'numeric',
  hour12: false,
  timeZone: 'America/Los_Angeles' 
}).format(date)
```

### Motivation

It would be great for developers just to pass it to their code and tweak it

**Comment by taras42** [comment]
@luisFilipePT I'd like to try this one.

**Comment by luisFilipePT** [comment]
@taras42 thanks, I'll assign it to you

**Comment by khuongTiet** [comment]
@luisFilipePT

Oh man, I actually added a PR for this just now!

**Comment by luisFilipePT** [comment]
@khuongTiet added you to contributors thanks
