### ISSUE TITLE
[FEATURE]: Improve SEO

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#41]
## Summary

Improve SEO to reach more audience and help more people!
To tags content and other suggestions add a comment here and tag me.

Lighthouse results are not bad but we can get them better 💪 

The goal here is to help SEO Overall to get better index from google and all the rest of the chambang related 😄  

Example gudelines: https://medium.com/@prestonwallace/3-ways-improve-react-seo-without-isomorphic-app-a6354595e400
![image](https://user-images.githubusercontent.com/9373787/66840087-66f87000-ef5f-11e9-8618-b4ccc6cdb910.png)

### Motivation

Reach more people and spread the knowledge

**Comment by coderavels** [comment]
I would love to contribute on this. @luisFilipePT

**Comment by luisFilipePT** [comment]
great @heisfullstacked go for it 🚀 , I'll assign it to you

**Comment by coderavels** [comment]
Getting 100 as SEO ranking in lighthouse. I guess I got late to work on this and someone already fixed it. 
<img width="703" alt="Screenshot 2019-10-22 at 2 01 46 AM" src="https://user-images.githubusercontent.com/38683602/67241034-4b65fb80-f470-11e9-81c4-e82f0bfd22df.png">

**Comment by coderavels** [comment]
@luisFilipePT Anything that needs to be done here? Or can we close this issue?

**Comment by luisFilipePT** [comment]
@heisfullstacked I think there is still stuff to be done we need react-helmet (https://github.com/nfl/react-helmet) and other improvements that allow us to be better ranked in google index.

Later on we will probably move the page to a better domain but for now the most important part is tags
