### ISSUE TITLE
[FEATURE]: Improve Accessibility

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#42]
## Summary

Improve SEO to reach more audience and help more people!
To tags content and other suggestions add a comment here and tag me.

Lighthouse results are not bad but we can get them better 💪 

The goal here is to help Accessibility to make the page available to all

![image](https://user-images.githubusercontent.com/9373787/66840352-d53d3280-ef5f-11e9-82ea-012175db608f.png)

### Motivation

Reach more people and spread the knowledge

**Comment by svnnynior** [comment]
can I take this ?

**Comment by luisFilipePT** [comment]
@svnnynior sure but please take a look at this PR #45 because I think it address's the same issue. And read the conversation

Get feedback from the author maybe?

I'll assign it to you and lets see how it goes 😄
