### ISSUE TITLE
[FEATURE]: Data for DateTimeFormat Form

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#5]
## Summary
Get from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat all possible data to be used in the form.
Connect what's possible
Brief explanation of the feature.

### Basic example
The locales and dateStyle are 2 examples already implemented
Omit this section if it's not applicable.

### Motivation
Have the more complete form possible

**Comment by flaviohenriqu** [comment]
@luisFilipePT I'll assign this for me

**Comment by luisFilipePT** [comment]
Go for it @flaviohenriqu 👍

**Comment by luisFilipePT** [comment]
thanks @flaviohenriqu
