### ISSUE TITLE
[FEATURE]: Add show code functionality

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#55]
## Summary

Similar to the copy to clipboard action on DateTimeFormat page implement the action to show the code (the button is already there) and you can probably use the output/logic of the copy action

### Basic example

1 - click the button
2 - open an antd popover or modal (check what feel nicer 😄 )
3 - Show the formatted code (maybe a package like this one 
https://www.npmjs.com/package/react-syntax-highlighter)
![image](https://user-images.githubusercontent.com/9373787/66858830-03cc0500-ef82-11e9-80c5-90afce0c0175.png)
Modal or popover sample content (this is dynamic like the copy to clipboard)
![image](https://user-images.githubusercontent.com/9373787/66859018-64f3d880-ef82-11e9-8be7-5ac0a3773853.png)

### Motivation

Give more options to the user

**Comment by singhsterabhi** [comment]
I want to work on this.

**Comment by luisFilipePT** [comment]
sure, assigned thanks 😉
