### ISSUE TITLE
[FEATURE]: Start laying out the Tests

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#61]
## Summary

As the project grows it comes the need to have a suit of tests that after will run on the pipeline and help guarantee the quality of the codebase.

### The plan is:
[ ] use Jest and Enzyme as the testing tools (open to other suggestions but react-testing-library we are not fans 😄 but maybe you can convince us)
[ ] start with unit tests
[ ] the tests files should be placed to the files they are testing
[ ] generation of code coverage and reports would be great
[ ] NO snapshot testing at this stage
[ ] am I forgetting something 🤔 😄  

### Motivation

Ease the work of everyone involved while maintaining some guarantees on the code and in the deployment pipeline

❤️ to ear more suggestions on this topic 👐

**Comment by khuongTiet** [comment]
Maybe you can have some git hooks with [husky](https://github.com/typicode/husky) and [eslint](https://github.com/eslint/eslint) to ensure clean code before every commit / push to the code base?

**Comment by luisFilipePT** [comment]
@khuongTiet yes, its already validates linting with *husky* on pre-commit 😄 

On tests I plan to do it on pre-push and again on pr-open 👍

**Comment by khuongTiet** [comment]
Ah, maybe we could add some extra eslint rules? Maybe something like [no-unused-vars](https://eslint.org/docs/rules/no-unused-vars) or some thing in addition to only having `prettier`

**Comment by singhsterabhi** [comment]
I am going to write some tests using Jest and Enzyme and raise PR.

**Comment by triartleet** [comment]
@luisFilipePT I am not that experienced in testing but I really want to start writing some. Therefore I will be lurking here a little and open some PRs on first chance. Maybe after this issue is closed in order to avoid conflicts with people working through hacktoberfest.

**Comment by luisFilipePT** [comment]
@fllprbt align with @singhsterabhi , after a PR with the installation and setup of `jest` and `enzyme` both of you can work on the issue and open different PR's focusing different files 😄
