### ISSUE TITLE
[BUG]: Remove unneeded variables in src/pages/DateTimeFormat/actions.js

### ISSUE THREAD

**Issue by jfrato** [xgeekshq/js-intl-kitchen-sink#65]
## Description

 - On line 21 src/pages/DateTimeFormat/actions.js there are unneeded variables (nu, ca, hc)

### Steps to reproduce

 - Check the src/pages/DateTimeFormat/actions.js on line 21

### Expected result

 - There should only be the locale var on src/pages/DateTimeFormat/actions.js line 21

### Actual result

What happened.

 - There are 3 unneeded variables on src/pages/DateTimeFormat/actions.js line 21 (nu, ca, hc)

**Comment by luisFilipePT** [comment]
@jratoxgeeks well catched feel free to open a PR for the fix 😄
