### ISSUE TITLE
[FEATURE]: Create PluralRules Page (core)

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#68]
## Summary

Create the core structure for the PluralRules page following the guidelines of:
https://js-intl-kitchen-sink.netlify.com/RelativeTimeFormat page
https://js-intl-kitchen-sink.netlify.com/DateTimeFormat page

Implement a clone from the examples given adapting the fields from the docs here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules

### Motivation

Move forward to have all pages completed

**Comment by coderavels** [comment]
I would like to work on this.

**Comment by luisFilipePT** [comment]
its yours @heisfullstacked

**Comment by coderavels** [comment]
Working on it today. Should raise a PR by eod.
