### ISSUE TITLE
[FEATURE]: Create ListFormat Page (core)

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#69]
## Summary

Create the core structure for the PluralRules page following the guidelines of:
https://js-intl-kitchen-sink.netlify.com/RelativeTimeFormat page
https://js-intl-kitchen-sink.netlify.com/DateTimeFormat page

Implement a clone from the examples given adapting the fields from the docs here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat

### Motivation

Move forward to have all pages completed

**Comment by cesar-cb** [comment]
Hey, it's me again :smile: Can i take this issue ?

**Comment by luisFilipePT** [comment]
@cesar-cb sure, many thanks for all the help 🥇
