### ISSUE TITLE
[FEATURE]: Copy to clipboard in RelativeTimeFormat page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#70]
## Summary

Implement copy to clipboard action in RelativeTimeFormat page similar to DateTimeFormat

### Basic example

![image](https://user-images.githubusercontent.com/9373787/66960506-80cfab00-f064-11e9-8dba-fc0615238a20.png)

### Motivation

Consistency across pages

**Comment by ogandose** [comment]
Hi, I would like to work on this 🙂

**Comment by luisFilipePT** [comment]
Go for it 🚀
