### ISSUE TITLE
[FEATURE]: Show code in RelativeTimeFormat page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#71]
## Summary

Implement show code action in RelativeTimeFormat page similar to DateTimeFormat

### Basic example

![image](https://user-images.githubusercontent.com/9373787/66960598-aceb2c00-f064-11e9-8eed-41a5dc1c291b.png)

### Motivation

Consistency across pages

**Comment by singhsterabhi** [comment]
I would like to do it.

**Comment by ogandose** [comment]
I don't think it makes sense to work on this in parallel to the clipboard  https://github.com/xgeekshq/js-intl-kitchen-sink/issues/70 since it's almost the same

**Comment by luisFilipePT** [comment]
> I don't think it makes sense to work on this in parallel to the clipboard #70 since it's almost the same

I don't see anything wrong with that 😄 , one of you might have a bit of extra work rebasing/merging and finding common ground. But @ogandose and @singhsterabhi maybe you can align? 😄 
There issues for everyone 🎉

**Comment by ogandose** [comment]
sure 🙂 I just meant it would mean writing the `getCodeSnippet` method twice 🙂
