### ISSUE TITLE
[FEATURE]: Reset in RelativeTimeFormat page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#72]
## Summary

Implement reset action in RelativeTimeFormat page similar to DateTimeFormat

### Basic example

![image](https://user-images.githubusercontent.com/9373787/66960690-ed4aaa00-f064-11e9-887d-4328a721b1ef.png)

### Motivation

Consistency across pages

**Comment by cesar-cb** [comment]
Could you please assign this issue to me ?

**Comment by luisFilipePT** [comment]
Sure @cesar-cb , have a 💥 😄
