### ISSUE TITLE
[BUG]: Reset in DateTimeFormat does not clear all fields

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#73]
## Description

Click on the reset action clears some fields but not all of them
![image](https://user-images.githubusercontent.com/9373787/66962551-2b49cd00-f069-11e9-9bde-07307718b128.png)

### Steps to reproduce

Just click on the reset action

### Expected result

All fields should be cleared

### Actual result

Some fields are not cleared

**Comment by gsilvamartin** [comment]
Please assign this to me.

**Comment by luisFilipePT** [comment]
@gsilvamartin go for it 🚀 , assigned
