### ISSUE TITLE
[FEATURE]: Browser Support Table on Home Page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#9]
## Summary

Add a Browser support table with the data provided https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl, check if it is possible to add column filter and sorting

Clear acknowledge the source of data, you see that around a lot 😄   

### Basic example

https://ant.design/components/table/#components-table-demo-head in the above table

### Motivation

This information is important enough to the users so don't make them have to jump between sites

**Comment by JoaoJesus94** [comment]
Hey, can I tackle on this one?

**Comment by luisFilipePT** [comment]
Sure, go for it 💯

**Comment by luisFilipePT** [comment]
Not stall.

**Comment by JoaoJesus94** [comment]
Still on it bot :D
